[project]
name = "rl-model"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gymnasium>=1.1.1",
    "numpy>=2.4.1",
    "pandas>=2.3.3",
    "ray[rllib]>=2.53.0",
]
